server.port=${PORT:8080}
spring.application.name=urlshortener
spring.datasource.url=jdbc:postgresql://ep-spring-pine-akcv0w5f-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NZ3VfQhXgaF4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.data.redis.url=rediss://default:gQAAAAAAAg8YAAIgcDJmZmEyODMwZmY1NmU0ODA0OGM4NTJiY2YwYzE0NDhmNw@exciting-marmot-134936.upstash.io:6379


